name: "Add a new dependency"
description: "Request to add a new Node.js dependency to the project"
title: "Add dependency: [package-name]"
labels: ["dependencies"]
body:
  - type: input
    id: package-name
    attributes:
      label: "Package Name"
      description: "Enter the name of the package to be added."
      placeholder: "e.g., lodash"
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: "Version (Optional)"
      description: "Specify a version if required."
      placeholder: "e.g., ^4.17.21"
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: "Reason for adding"
      description: "Explain why this dependency is needed."
      placeholder: "This package is required for..."
    validations:
      required: true
